name: FatherTedGraphQL
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node.js dependencies
        run: npm install
      - name: Run linters
        run: npm run lint
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test